export interface Doctor {
  universityName: string | null;
  prefix: string | null;
  fee: number | null;
  about: string | null;
  waitingTime: string | null;
  stateName: string | null;
  specialtyID: number;
  medicineTypeName: string | null;
  addressCountry: string | null;
  imgLoc: string | null;
  yearOfGraduation: number | null;
  updatedBy: number | null;
  docActive: number | null;
  addressType: string | null;
  univCityCode: string | null;
  universityCity: string | null;
  addressStateID: number | null;
  firstName: string;
  middleName: string | null;
  lastName: string | null;
  medicineTypeID: number;
  status: string | null;
  otherSpecializations: string | null;
  gender: number | null;
  videoService: number | null;
  addressCountryID: number | null;
  nationalRegDate: string | null;
  telephoneNos: string | null;
  degreeDescription: string | null;
  specialtyName: string | null;
  cityName: string | null;
  websiteUrl: string | null;
  universityCountry: string | null;
  ratingValueAverage: number | null;
  email: string | null;
  insuranceAccept: number | null;
  overallRating: number | null;
  degreeID: number | null;
  featuredDoctorDate: string | null;
  address1: string | null;
  address2: string | null;
  addressState: string | null;
  docID: number;
  verified: number | null;
  lastUpdatedDate: string;
  createdDate: string;
  createdBy: number | null;
  hospitalAffiliated: string | null;
  hospitalID: number | null;
  awards: string | null;
}
